from SocialNetwork.serializers.RegistrationSerializer import RegistrationSerializer
from SocialNetwork.serializers.LoginSerializer import LoginSerializer
from SocialNetwork.serializers.PostSerializer import PostSerializer
